eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: eurekaclient2
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
name: '{cipher}AQActygUJdhvslfrqxjF5rmtL/WIKdSzbISGOJJ8zjBOZPoVXt+H6vBMtTxjC59+/CMA3GEU5igMw9k2lrooxA2vaiByBp03xyXyaEEKOYjQZhBeODJ4oBrx6F03kPqMKXXNgCV8HLUIHHcvx/1NOa7mS+1UqPq/y8I9dhondOKZbCXuKHa2xZNVR65SDM8mbwWf/6vgqHL7AiEPHGa1hEgK5hCygOxj9iyQAVNH3nhUb1C+m4WE66DmI7/uJDntZ2fWsOUDEaLuLaDROOlW6YPr8N6r3WHSGP1An32TNHGEjrtHgqFzb1kZ1WC04oU23iGUMWKfyPBxSihDhKTNdv0NkrpFVRJ0KxwwSYZOB2ZmWyJ7S6hMXQ0gj0Yz0maljf4='
