eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
name: '{cipher}AQBbEEw7QBzMfQx4rQeaC30rfvYZoElXCMDYpM4EMLbeIfsOGYYudvzIRb4pzOvCJP9Yj67U8Ukvw1vW+TC3OArQCCjv/4rWy7ZMA6xupYd1iSJzYpJho1idy+Gg44CWRsgbVIPEbfxiAZAJW2gJN/IxWIdRONB/xySShfCjRmeYst26g0vRoAGmMPM+jqj022UdaRyy6GL7ktfP6vU3NYm9450O5K5VmzcVZY/nHq2tO8v2Shgo52HlXNZ1vXPKmByzoFiCDAcc8AAUt+KWf30PvOjIjLOJNgn7SU+oM6P3qzdfFehD4xC3CQ8d1ATpWsttDtneuA9JdXLK70+QlnPuxAXHuH/blYceoT2inRrkKb57+gJiDzSiYwb8ClgbevE='
