eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: eurekaclient2
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
name: '{cipher}AQAHFd3c1a+1KdRNw0XKAky4fhSf+qi2KPC77yk36St2EAZ4Z602+W1kZrrOhEeFxerHbQAhnwWjOEzoxy8TbyjDap1N+6h66TGzvCLpxb8JoRMXDQxzBWrzokKouwpn1CA7T808t3MbzrLBpSqzuwjMhM651ktzZagYlxP1SRYMsL5hcC7gp/H3Tk6bvIJu+ZBGy0Tdn+chTLiHQ4cuKBMCjOUGA9774QgL0X4Z1iF5dPmr04JrMzknjhxuqPNfNSRcQEhG+paXZZ1/Uy+KF4HaWZFcClRq62ICRIrosE2rvR9WiJT7U82lE6VmGQx7lZBzmtQSvl30aQFTuPU3yIV1N+UtMNouZeP3nMBeBxSmvf/D0sedDazAEsv2vhlBYak='
