eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
name: '{cipher}AQBRKHLM2HApICmnWjDUcFD95zn4mautnRNpe5+w4nqt1sROhZ+mHlHWP6P/VaXSDHDRIXyyY5z+0RrtYrHLBDgegSZ4EtWzjpbJkKbceLwRbuqDsFFeuLSeFN6r/EDk4RsjDozRHuC5BBHZAcJU6LMnNFp8kPazhEib/EbdmAmavT0n0/DkOYJ2L/F63aLzKKwmtRtVapsdEw5L3W4Ypf7Z8OwHYn+/OverHyVR/VMj8ZN3eHbS6awQI6liTkyzFNsIgti3k8LsQg1CP8SMsungFYDIdCD7FjP3RCahz/sa0Et3AmU2IWVBSPYHkVXjucrblx37bW3cyF/DG/qSE5rn6WB5x5MjDkMuaYMU9vV+etE/cMzwjzGyD2RT+Vhnoeo='
