eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
name: '{cipher}AQADqUVhApjncYLLK2FytL9C+snDmlRUYxqy4LgAk+wzh3ekNav/gXlLPa9GGEy/2s8GBzVPP7AUFcw6ypWgUfXk9Xk9d6Zej356qkcuIl7peL3NSwx0rj0Eww+LQoZv8+iONzV8BUY3RlLKYW9IJXpZ1BeX5D7TBJ3gCPQIJMgRedH6xqCrsOS4UrTTCk2r9j1RwkE/xSjv/guUwZJPER3uca/8+8WxPQkltAGAB3d603A3KufqGLjENIWdX+vBX2PubGQR4qGPszPbma/okd3hml6+XSfiiAvnJNBzoPXVH3I8lo7Ww4dw/gS4dYi1F8fzmFMp2VdZYT2fWKwu/oJCTSCpWzKX6qirZeHAAYIcwsEcnUHUIeF3OkRFGfQ1gw0='
