eureka:
  instance:
    hostname: localhost
    instance-id: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
name: '{cipher}AQAXRcgvEPnFZI+YbelA1BA8aOLNgBNYDy4hyk4t4BMmc1x0HKl4W0SglUqDd/JDOGjw522utsgEnMvlYrSLsVY2+C57J97IakjUt2R9vcPEKbG6R425BDBWXVpF6mQ31FMBKgRYsg+O9D7i7LlA0IPXdyqzDZ4Ue4zwlWhLuwIpxrt+lhz4o+ZVIBlhqgeeVGbASaYLgThKevge9AxVcDpk029aOI/5LHquqcNf4uHVHsOOn5UGIG3U123XuSBimeEckxpuBy0wTU27qhhO5zdeCyDf6kkwfk23prv9owsBO2INbktYsRHccu2sJKaLSpBQOajl0e2iNEQqyrlZVe+b+t/rYJaMHTTPSkzAk3GirOzlKUI6WKXH09XE0WPIOso='
